# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b2b2b047625682bb5a6b35b96c881dcac60adebcf6c1205c2c9492973656c007a3ec224dc6aa91dc6ad275daa4da61b8e2ac44a98d0c32082b00077cfc6f5d1

test:
  secret_key_base: c97f8cbd2a42369f08d132e2db294de2ea72600ed295631d282276dad2bdb2322847fb4b3be0d147c69c34fba8a3189d9b94d377521288ee7d08f2946f6e5945

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
